server:
<<<<<<< HEAD
  port: 8083

spring:
  application:
    name: SENSOR-TELEMETRY-SERVICE
=======
<<<<<<< HEAD
  port: 8082  # Zone Service runs on 8082

spring:
  application:
    name: ZONE-SERVICE  # Eureka name (uppercase)
>>>>>>> 3b3c73743e23f5161373c146a6d8d70c6af8d4f4

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
<<<<<<< HEAD
    fetch-registry: true
=======
    fetch-registry: true
=======
<<<<<<< HEAD
  port: 8090   # Gateway run ??? port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Config Server route
        - id: config-server
          uri: http://localhost:8888
          predicates:
            - Path=/config-server/**

        # Eureka-registered service route
        - id: greenhouse-service
          uri: lb://GREENHOUSE-SERVICE
          predicates:
            - Path=/service/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
=======
<<<<<<< HEAD
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/chathu-2003/Autometed_GreenHouse_Management_System
          default-label: main
=======
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
>>>>>>> 496e4d6e294a3331dd507ab85ce3daed40fa75c0
>>>>>>> a9e6f14f74fc46a70cd586c5d324e87200bddc08
>>>>>>> e72185d86817a617a7f4c9a61e55141f27322c76
>>>>>>> 3b3c73743e23f5161373c146a6d8d70c6af8d4f4
